name: Build Elixir

on:
  pull_request:
    branches:
      - main

env:
  MIX_ENV: test
  CACHE_VERSION: v0

defaults:
  run:
    working-directory: elixir

jobs:
  build:
    name: Build & test
    runs-on: ubuntu-latest
    timeout-minutes: 15

    strategy:
      matrix:
        elixir:
          - "1.15"
        otp:
          - "25"
        rust:
          - stable

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Restore dependencies cache
        uses: actions/cache@v2
        id: deps_cache
        with:
          path: backend/deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ env.CACHE_VERSION }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ env.CACHE_VERSION }}-

      - name: Restore _build cache
        uses: actions/cache@v2
        id: build_cache
        with:
          path: backend/_build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{ env.CACHE_VERSION }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-build-${{ env.CACHE_VERSION }}-

      - name: Setup Rust (for NIFs)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Restore Cargo dependencies cache
        uses: Swatinem/rust-cache@v1

      - name: Install dependencies
        # if: steps.deps_cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Compile dependencies
        if: steps.deps_cache.outputs.cache-hit != 'true'
        run: mix deps.compile

      - name: Compile
        run: mix compile
        env:
          RUSTLER_PRECOMPILATION_FORCE_BUILD: "true"

      - name: Check formatting
        run: mix format --check-formatted

      - name: Run Credo
        id: credo
        if: github.event_name == 'pull_request'
        run: mix credo suggest --min-priority normal --config-file=.credo.exs --format=oneline

      - name: Run tests
        id: tests
        run: mix coveralls
